spring:
  datasource:
    url: jdbc:h2:mem:librarydb
    initialization-mode: always
  mvc:
    log-request-details: true
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

debug: on
logging.level.org.springframework.web: DEBUG
